# Labor Supply

## Static Model

### Substitution and Income Effects

まずは静学的な労働供給モデルを考えます. 家計は以下の効用最大化問題を解きます:

$$
\max_{c, h} u(c, h) \quad \text{ s.t. } c \leq w h + I.
$${#eq-labor-static}

ここで, 消費 $c \geq 0$, 労働供給 $h \geq 0$, 賃金率 $w > 0$, 非労働所得 $I \geq 0$ です. また, 賃金率 $w$ と非労働所得 $I$ に対する労働供給を $h(w, I)$ とします. この時, 労働供給の弾力性は以下で定義されます:

$$
\begin{aligned}
\eta_{h, w}^M &= \frac{\partial h(w, I)}{\partial w} \frac{w}{h(w, I)} \\
\eta_{h, I} &= \frac{\partial h(w, I)}{\partial I} \frac{I}{h(w, I)}
\end{aligned}
$$

特に, 所得を一定とした時の賃金弾力性 $\eta_{h, w}^M$ をマーシャリアン弾力性 (Marshallian elasticity) と呼びます. 次に, 労働供給の代替効果と所得効果を分離するために, ヒックス弾力性 (Hicksian elasticity) を導入します. 家計は以下の支出最小化問題を解きます:

$$
\min_{c, h} c - wh \quad \text{ s.t. } u(c, h) \geq \bar{u}.
$$

ここで, 効用水準 $\bar{u}$ に対する労働供給を $h^H(w, \bar{u})$ とします. この時, ヒックス弾力性は以下で定義されます:

$$
\eta_{h, w}^H = \frac{\partial h^H(w, \bar{u})}{\partial w} \frac{w}{h^H(w, \bar{u})}.
$$

::: {.callout-note}

## スルツキーの恒等式 (Slutsky Equation)

所得 $I$, 価格ベクトル $\mathbf{p}$ のもとで次の家計の効用最大化問題を考える.

$$
\max_{\mathbf{x}} u(\mathbf{x}) \quad \text{ s.t. } \mathbf{p}^{\top} \mathbf{x} \leq I.
$$

この時, 財 $i$ の最適消費を $x_i(\mathbf{p}, I)$ とする. また, 効用水準 $\bar{u}$ に対する支出最小化問題を考える.

$$
\min_{\mathbf{x}} \mathbf{p}^{\top} \mathbf{x} \quad \text{ s.t. } u(\mathbf{x}) \geq \bar{u}.
$$

この時, 財 $i$ の最適消費を $x_i^H(\mathbf{p}, \bar{u})$ とし, 支出関数を $I(\mathbf{p}, \bar{u})$ とする.  連鎖律から次の式を得る.

$$
\frac{\partial x_i^H(\mathbf{p}, \bar{u})}{\partial p_i} = \frac{\partial x_i(\mathbf{p}, I(\mathbf{p}, \bar{u}))}{\partial p_i} + \frac{\partial x_i(\mathbf{p}, I(\mathbf{p}, \bar{u}))}{\partial I(\mathbf{p}, \bar{u})} \frac{\partial I(\mathbf{p}, \bar{u})}{\partial p_i}
$$

また, シェファードの補題 (Shephard's lemma) $\frac{\partial I(\mathbf{p}, \bar{u})}{\partial p_i} = x_i^H(\mathbf{p}, \bar{u})$ より,

$$
\frac{\partial x_i}{\partial p_i} = \frac{\partial x_i^H(\mathbf{p}, \bar{u})}{\partial p_i} - \frac{\partial x_i(\mathbf{p}, I)}{\partial I} x_i^H(\mathbf{p}, \bar{u}).
$$

これをスルツキーの恒等式 (Slutsky equation) と呼ぶ.

:::

労働供給の問題は価格1の財と価格 $-w$ の労働の2財問題とみなせるため,

$$
\frac{\partial h(w, I)}{\partial w} = \frac{\partial h^H(w, \bar{u})}{\partial w} + \frac{\partial h(w, I)}{\partial I} h^H(w, \bar{u}).
$$

ここで, 価格が負であるためシェファードの補題が $\frac{\partial I(w, \bar{u})}{\partial w} = -h^H(w, \bar{u})$ となることに注意してください. 全体を $\frac{w}{h}$ で掛けると^[
    均衡において $h(w, I) = h^H(w, \overline{u})$ であるため, 右辺の $h(w, I)$ を $h^H(w, \overline{u})$ に置き換えても問題ありません.
],

$$
\underbrace{\frac{\partial h(w, I)}{\partial w} \frac{w}{h}}_{\eta_{h, w}^M} = \underbrace{\frac{\partial h^H(w, \bar{u})}{\partial w} \frac{w}{h}}_{\eta_{h, w}^H} + \underbrace{\frac{\partial h(w, I)}{\partial I} \frac{I}{h}}_{\eta_{h, I}} \frac{wh}{I}.
$$

この式は, 労働供給の弾力性が次の代替効果と所得効果の和に分解されることを示しています.

- **代替効果**: 賃金の増加によって労働のリターンが増加し, 労働供給を増やす効果. 余暇の価格 (労働の機会費用) の増加に対する財への代替と考えてもよい
- **所得効果**: 所得の増加によって働く必要がなくなり, 労働供給を減らす効果. 余暇が正常財である場合, 所得の増加によって余暇の消費が増加し, 労働供給が減少すると考えてもよい

### Examples

::: {#exm-labor-loglog}

## Cobb-Douglas Utility

$$
\max_{c, l}  (1-\phi) \log c + \phi \log l \quad \text{ s.t. } c \leq w(1-l) + I.
$$
$$
\eta_{h, w}^M = \frac{\phi}{w}\frac{I}{h},
$$

- 代替効果: $\eta_{h, w}^H = \frac{\phi}{w}\frac{I}{h} + \phi$
- 所得効果: $\eta_{h, I}\frac{wh}{I}=-\phi$

$I = 0$ の時, 代替効果 $\phi$ と所得効果 $\phi$ が打ち消しあい, 労働供給の賃金弾力性は0となる.

:::

::: {.proof}

最適条件より,

$$
h(w, I) = 1 - \phi\left(1 + \frac{I}{w}\right).
$$

よって,

$$
\begin{aligned}
\eta_{h, w}^M &= \frac{\partial h(w, I)}{\partial w} \frac{w}{h(w, I)} = \frac{\phi I}{w^2} \frac{w}{h(w, I)} = \frac{\phi}{w}\frac{I}{h(w, I)}\\
\eta_{h, I} &= \frac{\partial h(w, I)}{\partial I} \frac{I}{h(w, I)} = -\frac{\phi}{w} \frac{I}{h(w, I)}.
\end{aligned}
$$

スルツキーの恒等式より,

$$
\eta_{h, w}^H = \eta_{h, w}^M - \eta_{h, I} \frac{wh(w, I)}{I} = \frac{\phi}{w}\frac{I}{h(w, I)} + \phi.
$$

**費用最小化問題**

スルツキーの恒等式を確認するために, ヒックス弾力性を定義から計算する.

$$
\min_{c, l} c - w(1-l) \quad \text{ s.t. } (1-\phi) \log c + \phi \log l \geq \bar{u}.
$$

ラグランジアン $\mathcal{L} = c - w(1-l) + \lambda \left(\bar{u} - (1-\phi) \log c - \phi \log l \right)$ の最適条件は次の通り.

$$
\begin{aligned}
\frac{\partial \mathcal{L}}{\partial c} &= 1 - \lambda \frac{1-\phi}{c} = 0, \\
\frac{\partial \mathcal{L}}{\partial l} &= w - \lambda \frac{\phi}{l} = 0, \\
\frac{\partial \mathcal{L}}{\partial \lambda} &= \bar{u} - (1-\phi) \log c - \phi \log l = 0.
\end{aligned}
$$

一階条件から, $c = \frac{1-\phi}{\phi}wl$ より, 効用制約に代入すると,

$$
\bar{u} = (1-\phi) \log \left(\frac{1-\phi}{\phi}wl\right) + \phi \log l = (1-\phi) \log \left(\frac{1-\phi}{\phi}w\right) + \log l.
$$

よって, 関数 $A(\bar{u}; \phi)$ を用いて, $l = A(\bar{u}; \phi) w^{-(1-\phi)}$ と表せるので,

$$
h^H(w, \bar{u}) = 1 - A(\bar{u}; \phi) w^{-(1-\phi)}.
$$

ヒックシアン弾力性は定義から,

$$
\begin{aligned}
\eta_{h, w}^H &= \frac{\partial h^H(w, \bar{u})}{\partial w} \frac{w}{h^H(w, \bar{u})}\\
&= (1-\phi) A(\bar{u}; \phi) w^{-(1-\phi)-1} \frac{w}{h^H(w, \bar{u})} \\
&= (1-\phi) \frac{1 - h^H(w, \bar{u})}{h^H(w, \bar{u})} & \because 1 - h^H(w, \bar{u}) = A(\bar{u}; \phi) w^{-(1-\phi)} \\
\end{aligned}
$$

ここで一階条件から $1 - h^H(w, \bar{u}) = \frac{\phi}{1-\phi}\frac{c}{w}$ であり, 均衡における予算制約 $c = w h^H(w, \bar{u}) + I$ を用いると,

$$
\begin{aligned}
\eta_{h, w}^H &= \frac{\phi}{w} \frac{c}{h^H(w, \bar{u})} \\
&= \frac{\phi}{w} \frac{w h^H(w, \bar{u}) + I}{h^H(w, \bar{u})} \\
&= \frac{\phi}{w} \frac{I}{h^H(w, \bar{u})} + \phi.
\end{aligned}
$$

:::
 
## Dynamic Model

次の動学的労働供給モデルを考えます:

$$
V(a) = \max_{c, h, a'} u(c, h) + \beta V(a') \quad \text{s.t. } c + a' = (1 + r)a + wh.
$$

ここで, $I := (1+r)a - a'$ と置くと, 静学的な労働供給モデル (-@eq-labor-static) と同じ形になります. 動学的な労働供給モデルにおける賃金弾力性には, 主に次の3種類があります.

1. Marshallian 弾力性: 所得を一定とした下での労働供給の弾力性
2. Hicksian 弾力性: 効用のレベルを一定とした下での労働供給の弾力性
3. Frisch 弾力性: 限界効用を一定にした下での労働供給の弾力性

**Marshallian & Hicksian Elasticities**

Marshallian 弾力性は, 静学的な労働供給と同様に定義することが可能です. 直感的には, 賃金が下落した際に貯金を切り崩すといった埋め合わせ (compensation) 行動は可能ですが, その点を考慮せずに, 所得 $I$ を一定とした下での労働供給の弾力性として定義されます. その意味でMarshallian 弾力性は uncompesated elasticity とも呼ばれます.

Hicksian 弾力性も静学的な労働供給と同様に定義することが可能です. 賃金が下落した際に貯金を切り崩すことで効用水準を一定に保つ状況を考えるという意味で, Hicksian 弾力性は compensated elasticity とも呼ばれます.

::: {#exm-labor-crra}

## CRRA Utility

$$
u(c, h) = \frac{c^{1-\sigma}-1}{1-\sigma} - \psi \frac{h^{1+\frac{1}{\gamma}}}{1+\frac{1}{\gamma}}.
$$

$$
\eta_{h, w}^M = \frac{1 - \sigma(1-s)}{\frac{1}{\gamma} + \sigma(1-s)}.
$$

- 代替効果: $\eta_{h, w}^H = \frac{1}{\frac{1}{\gamma} + \sigma(1-s)}$
- 所得効果: $\eta_{h, I}\frac{wh}{I} = -\frac{\sigma - \sigma s}{\frac{1}{\gamma} + \sigma(1-s)}$

where $s = \frac{I}{c}$.



:::

::: {.proof}

Intra-temporal な最適条件より,

$$
c^{-\sigma} w = \psi h^{\frac{1}{\gamma}}.
$${#eq-labor-crra-intra}

対数をとって, $\log w$ で微分すると,

$$
-\sigma \frac{\partial \log c}{\partial \log w} + 1 = \frac{1}{\gamma} \frac{\partial \log h}{\partial \log w}.
$${#eq-labor-crra-intra-wage}

予算制約 $\log c = \log (w h + I)$ を $\log w$ で微分すると,

$$
\begin{aligned}
\frac{\partial \log c}{\partial \log w} &= \frac{1}{wh + I}\frac{\partial (wh+I)}{\partial w}\frac{\partial w}{\partial \log w} \\
&= \frac{wh}{wh + I}\left(1 + \frac{\partial \log h}{\partial \log w}\right)\\
&= (1 - s) \left(1 + \frac{\partial \log h}{\partial \log w}\right).
\end{aligned}
$$

これを @eq-labor-crra-intra-wage に代入すると,

$$
\eta_{h, w}^M = \frac{\partial \log h}{\partial \log w} = \frac{1 - \sigma(1-s)}{\frac{1}{\gamma} + \sigma(1-s)}.
$$

@eq-labor-crra-intra の対数を取って, $\log I$ で微分すると,

$$
-\sigma \frac{\partial \log c}{\partial \log I} = \frac{1}{\gamma} \frac{\partial \log h}{\partial \log I}.
$${#eq-labor-crra-intra-income}

予算制約 $\log c = \log (w h + I)$ を $\log I$ で微分すると,

$$
\begin{aligned}
\frac{\partial \log c}{\partial \log I} &= \frac{1}{wh + I}\frac{\partial (wh+I)}{\partial \log I} \\
&= \frac{1}{wh + I}\left(wh\frac{\partial \log h}{\partial \log I} + I\right)\\
&= \frac{1}{c}\left((c-I)\frac{\partial \log h}{\partial \log I}+ I\right) \\
&= (1 - s) \frac{\partial \log h}{\partial \log I}+ s.
\end{aligned}
$$

これを @eq-labor-crra-intra-income に代入すると,

$$
\eta_{h, I} = \frac{\partial \log h}{\partial \log I} = -\frac{\sigma s}{\frac{1}{\gamma} + \sigma(1-s)}.
$$

スルツキーの恒等式より,

$$
\begin{aligned}
\eta_{h, w}^H &= \eta_{h, w}^M - \eta_{h, I} \frac{wh}{I} \\
&= \frac{1 - \sigma(1-s)}{\frac{1}{\gamma} + \sigma(1-s)} + \frac{\sigma s}{\frac{1}{\gamma} + \sigma(1-s)} \left(\frac{1}{s} - 1\right) \\
&=\frac{1}{\frac{1}{\gamma} + \sigma(1-s)}.
\end{aligned}
$$

:::

**Frisch Elasticity**

Frisch 弾力性は, 消費の限界効用を一定にした下での労働供給の弾力性として定義されます. また, しばしば lifetime wealth に対する限界効用を一定にした下での労働供給の弾力性としても定義されます. これは恒常所得仮説 (permanent income hypothesis) に基づくと, 消費の限界効用が lifetime wealth のみに依存すると考えるためです.

直感的には, 一時的な賃金の上昇は lifetime wealth にほとんど影響を与えないため, Frisch 弾力性は一時的な賃金変動に対する労働供給の反応を捉えると考えられます. そのため, RBCモデルなどで確率過程に基づく賃金変動が考慮される場合, Frisch 弾力性が重要な役割を果たします.

一階条件から, ラグランジュ乗数は $\lambda = u_c(c, h)$ であり, Frish 弾力性はこの $\lambda$ を一定にした下での労働供給の弾力性として定義されます. すなわち, $u_h(c, h) = -\lambda w$ より, 

$$
u_{cc} \frac{\partial c}{\partial w} + u_{ch} \frac{\partial h}{\partial w} = 0 \text{ and }
u_{hc} \frac{\partial c}{\partial w} + u_{hh} \frac{\partial h}{\partial w} = -\lambda.
$$

これを $\frac{\partial h}{\partial w}$ について解くと,

$$
\frac{\partial h}{\partial w} = \frac{u_{h}}{u_{hh} - \frac{u_{ch}^2}{u_{cc}}} \frac{1}{w}.
$$

Frisch 弾力性 $\eta_{h, w}^F := \frac{\partial h}{\partial w}\frac{w}{h}|_{\lambda}$ より,

$$
\eta_{h, w}^F = \frac{u_{h}}{h\left(u_{hh} - \frac{u_{ch}^2}{u_{cc}}\right)}.
$$

なお, この式から自明に @exm-labor-crra において $\eta_{h, w}^F = \gamma$ となります. @chetty2011 はメタ分析を行い, Frisch 弾力性の平均的な推定値を報告しました.

- **ミクロ分析** (擬似実験, quasi-experiment): 0.82
- **マクロモデル**: 2.84

マクロモデルの結果は, RBCモデルなどで雇用は実質賃金よりも volatile であることを反映しています. この「マクロモデルの Frisch 弾力性はミクロ分析よりもかなり大きい」というPuzzleに関しては今も議論が続いています (e.g., @erosa2016).
